#!/bin/sh
#
# @name Gazebo x500
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=mosquito}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.11
param set-default CA_ROTOR0_PY 0.11
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.11
param set-default CA_ROTOR1_PY -0.11
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.11
param set-default CA_ROTOR2_PY -0.11
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.11
param set-default CA_ROTOR3_PY 0.11
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

param set-default MPC_THR_HOVER 0.32

# Control Parameters
param set-default MPC_ACC_HOR_MAX 12.0
param set-default MPC_ACC_UP_MAX 10.0
param set-default MPC_MAN_TILT_MAX 55.0
param set-default MPC_TILTMAX_AIR 65.0
param set-default MPC_XY_VEL_MAX 20.0
param set-default MPC_Z_VEL_MAX_UP 8.0


# Logging Parameters
param set-default SDLOG_PROFILE 0
param set-default SDLOG_MODE 0

#Failsafe parameters
param set-default NAV_RCL_ACT 1

# DDS parameters

#use gazebo clock for synchronization
param set-default UXRCE_DDS_SYNCT 0

